# Linear Algebra for CpE
## Laboratory 6 : Matrices

Coded and submitted by:
<br>
Panelo, Bryan V.
<br>
58011

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

### Matrices

## Activity

### Task 1

Create a function named `mat_desc()` that througouhly describes a matrix, it should: <br>
1. Displays the shape, size, and rank of the matrix. <br>
2. Displays whether the matrix is square or non-square. <br>
3. Displays whether the matrix is an empty matrix. <br>
4. Displays if the matrix is an identity, ones, or zeros matrix <br>
   
Use 5 sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [83]:
## Function area
def mat_desc(matrix):
    mshape = print("The shape of the matrix is:",matrix.shape)
    msize  = print("The size of the matrix is:", matrix.size)
    mrank  = print("The rank of the matrix is:", matrix.ndim)
        
        #matrix and non matrix
    if matrix.shape[0] == matrix.shape[1]:
        print("The matrix is a square")
    else:
        print("The matris is non-square")

        #Whether the matrix is empty
    if matrix.size > 0:
        print("The matrix is not null")
    else:
        print("The matrix is null")
    
        #Display if the matrix is an identity
    
    if (np.eye(matrix.shape[0],matrix.shape[1])).any(): 
          print("The matrix is an identity")
    elif (np.eye(matrix.shape[0]!=matrix.shape[1])).any(): 
           print("The matrix is not an identity")
    else:0
        #Display if the matrix is comprised of ones
    if np.all(matrix) == 1:
        print("The matrix is a ones matrix")
    else: 
        print("The matrix is not is not a ones matrix")
        
        #Display if the matrix is coprised of zeros
    if np.all(matrix) ==0:
        print("The matrix is comprised of zeros")
    elif np.all(matrix) !=0:
        print("The matrix is not comprised of zeros")

In [3]:
## Matrix declarations
A = np.array([
    [0,0,0],
    [0,0,0],
    [0,0,0]
])

B = np.array([
    [1,3,1],
    [0,5,2],
])
C = np.array([
    [1,0,0],
    [0,1,0],
    [0,0,1]
])
D = np.array([
    [1,1,1],
    [1,1,1],
    [1,1,1]
])
E = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])


In [84]:
## Test Areas
print("---A---")
mat_desc(A)

print("---B---")
mat_desc(B)

print("---C---")
mat_desc(C)

print("---D---")
mat_desc(D)

print("---E---")
mat_desc(E)

---A---
The shape of the matrix is: (3, 3)
The size of the matrix is: 9
The rank of the matrix is: 2
The matrix is a square
The matrix is not null
The matrix is an identity
The matrix is not is not a ones matrix
The matrix is comprised of zeros
---B---
The shape of the matrix is: (2, 3)
The size of the matrix is: 6
The rank of the matrix is: 2
The matris is non-square
The matrix is not null
The matrix is an identity
The matrix is not is not a ones matrix
The matrix is comprised of zeros
---C---
The shape of the matrix is: (3, 3)
The size of the matrix is: 9
The rank of the matrix is: 2
The matrix is a square
The matrix is not null
The matrix is an identity
The matrix is not is not a ones matrix
The matrix is comprised of zeros
---D---
The shape of the matrix is: (3, 3)
The size of the matrix is: 9
The rank of the matrix is: 2
The matrix is a square
The matrix is not null
The matrix is an identity
The matrix is a ones matrix
The matrix is not comprised of zeros
---E---
The shape of the 

### Task 2

Create a function named `mat_operations()` that takes in two matrices or scalars a input parameters it should:<br>
 1. Display the description of each matrix, if the parameter is a scalar it tells that it is a scalar rather than describing it as a matrix.
 2. Determines if the matrices are viable for operation and returns your own error message if they are not viable.
 3. Returns the sum of the matrices.
 4. Returns the differen of the matrices.
 5. Returns the element-wise multiplication of the matrices.
 6. Returns the element-wise division of the matrices.

Use 5 sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [5]:
def mat_operations(matrixA,matrixB):
    if (matrixA.shape==matrixB.shape):
        print("The sum of the matrices is:\n", matrixA+matrixB)
        print("The difference of the matrices is:\n", matrixA-matrixB)
        print("The product of the matrices is:\n", matrixA*matrixB)
        print("The quotient ofa the matrices is:\n", matrixA/matrixB)
    elif matrixA.shape!=matrixB.shape:
        print("The metrices are not equal therefore it is not viable for operations")
    else: 0

In [87]:
A2 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
B2 = np.array([
    [1,2,3],
    [4,5,6],
    [6,5,4],
    [1,2,1]
])
C2 = np.array([
    [1,2,2],
    [1,2,1],
    [3,2,1]
])
D2 = np.array([
    [2,2,2],
    [3,3,3],
    [1,4,4]
])
E2 = np.array([
    [1,2,2],
    [3,3,2],
    [1,2,4]
])

In [88]:
print("Metrices A2 and B2:")
mat_operations(A2,B2)
print("-----------------------------------------------------")
print("Metrices C2 and D2:\n")
mat_operations(C2,D2)
print("-----------------------------------------------------")
print("Metrices A2 and E2:\n")
mat_operations(A2,E2)

Metrices A2 and B2:
The metrices are not equal therefore it is not viable for operations
-----------------------------------------------------
Metrices C2 and D2:

The sum of the matrices is:
 [[3 4 4]
 [4 5 4]
 [4 6 5]]
The difference of the matrices is:
 [[-1  0  0]
 [-2 -1 -2]
 [ 2 -2 -3]]
The product of the matrices is:
 [[2 4 4]
 [3 6 3]
 [3 8 4]]
The quotient ofa the matrices is:
 [[0.5        1.         1.        ]
 [0.33333333 0.66666667 0.33333333]
 [3.         0.5        0.25      ]]
-----------------------------------------------------
Metrices A2 and E2:

The sum of the matrices is:
 [[ 2  4  5]
 [ 7  8  8]
 [ 8 10 13]]
The difference of the matrices is:
 [[0 0 1]
 [1 2 4]
 [6 6 5]]
The product of the matrices is:
 [[ 1  4  6]
 [12 15 12]
 [ 7 16 36]]
The quotient ofa the matrices is:
 [[1.         1.         1.5       ]
 [1.33333333 1.66666667 3.        ]
 [7.         4.         2.25      ]]
